version: "3.8"
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_USER: ${POSTGRES_DB_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    restart: always
    ports:
      - ${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    depends_on:
      - postgres
    ports:
      - ${PGADMIN_PORT}:${PGADMIN_PORT}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    environment:
      HOST: ${APP_HOST}
      PORT: ${APP_PORT}
      POSTGRES_DB_HOST: postgres
      POSTGRES_DB_PORT: ${POSTGRES_DB_PORT}
      POSTGRES_DB_USERNAME: ${POSTGRES_DB_USERNAME}
      POSTGRES_DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - ${APP_PORT}:${APP_PORT}

#  nginx:
#    image: nginx:1.17.1-alpine
#    container_name: nginx
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#    ports:
#      - ${NGINX_PORT}:${NGINX_PORT}
#    links:
#      - client
#      - server
#    depends_on:
#      - client
#      - server
