version: "3"
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: main_db
      POSTGRES_USER: vlad
      POSTGRES_PASSWORD: password
    restart: always

  app:
    image: fullstack_app
    container_name: app
    environment:
      HOST: localhost
      PORT: 3000
      POSTGRES_DB_HOST: localhost
      POSTGRES_DB_PORT: 5432
      POSTGRES_DB_USERNAME: vlad
      POSTGRES_DB_PASSWORD: password
    ports:
      - "3000:3000"
    links:
      - postgres
    restart: always


  nginx:
    image: nginx:1.17.1-alpine
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app

