export type ImageName = (
  'error-background'
  | 'material-book'
  | 'mesh-support'
  | 'partner-logo'
  | 'placeholder-books-1'
  | 'placeholder-diagram-1'
  | 'placeholder-diagram-2'
  | 'placeholder-diagram-3'
  | 'placeholder-diagram-4'
  | 'placeholder-geometry-1'
  | 'placeholder-men-orange-1'
  | 'placeholder-men-orange-2'
  | 'placeholder-men-purple-1'
  | 'placeholder-woman-crimson-1'
  | 'placeholder-woman-orange-1'
)
