name: telegram
on:
  push:
  pull_request:
  
jobs:
  telegram:
    runs-on: ubuntu-latest
    steps:
    - name: send telegram message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: send photo message
