name: telegram
on: [push, pull_request, watch]

jobs:
  telegram:
    runs-on: ubuntu-latest
    steps:
    - name: send telegram message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
            Произошли изменения:
            
            Пользователь: ${{ github.actor }}
            Действие: ${{github.event_name}}:
            
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            Посмотреть изменения: https://github.com/${{ github.repository }}/commit/${{github.sha}}
